
PRODUCT_PACKAGES += \
    at_distributor.rc \
    autotest.rc \
    bcsdaemon.rc \
    charon.rc \
    chown_service.rc \
    cmd_services.rc \
    cp_diskserver.rc \
    data.rc \
    download.rc \
    drdaemon.rc \
    engpc.rc \
    gpsd.rc \
    hostapd.rc \
    inputfreq.rc \
    ipsecdaemon.rc \
    kill_phone.rc \
    macloader.rc \
    mfgloader.rc \
    modem_control.rc \
    modemd.rc \
    modemDriver.rc \
    p2p_supplicant.rc \
    phoneserver.rc \
    prepare_param.rc \
    recoveryfreq.rc \
    refnotify.rc \
    set_mac.rc \
    slog.rc \
    slogmodem.rc \
    smddaemon.rc \
    smd_symlink.rc \
    sswap.rc \
    umount_service.rc \
    wcnd.rc \
    wlandutservice.rc \
    wpa_supplicant.rc \
    zram.rc
