/*
 * CSC Features
 * Auto generated by gen_cscfeaturetag_ih.pl
 * DO NOT EDIT THIS FILE
 */

/*
#include "SecNativeFeatureTagGMS.h"
#include "SecNativeFeatureTagMediaProvider.h"
#include "SecNativeFeatureTagNFC.h"
#include "SecNativeFeatureTagStreaming.h"
#include "SecNativeFeatureTagWiFi.h"
#include "SecNativeFeatureTagBT.h"
#include "SecNativeFeatureTagFramework.h"
#include "SecNativeFeatureTagWeb.h"
*/

#include "SecNativeFeatureTagCommon.h"
#include "SecNativeFeatureTagIMS.h"
#include "SecNativeFeatureTagRIL.h"
#include "SecNativeFeatureTagVoiceCall.h"

